import { Knex } from 'knex';
import bcrypt from 'bcrypt';

/**
 * Test user seeds for development and testing
 * CRITICAL: NO child data - only parent profiles with child counts/age ranges
 */
export async function seed(knex: Knex): Promise<void> {
  // Clear existing data in reverse dependency order
  await knex('payments').del();
  await knex('household_members').del();
  await knex('households').del();
  await knex('messages').del();
  await knex('conversations').del();
  await knex('matches').del();
  await knex('verifications').del();
  await knex('profiles').del();
  await knex('users').del();

  const hashedPassword = await bcrypt.hash('TestPassword123!', 10);

  // Insert test users with varied verification statuses
  const users = await knex('users')
    .insert([
      {
        email: 'sarah.verified@test.com',
        password_hash: hashedPassword,
        phone: '+15551234567',
        phone_verified: true,
        email_verified: true,
        two_factor_enabled: false,
        status: 'active',
      },
      {
        email: 'maria.fullverified@test.com',
        password_hash: hashedPassword,
        phone: '+15551234568',
        phone_verified: true,
        email_verified: true,
        two_factor_enabled: true,
        status: 'active',
      },
      {
        email: 'lisa.pending@test.com',
        password_hash: hashedPassword,
        phone: '+15551234569',
        phone_verified: false,
        email_verified: true,
        two_factor_enabled: false,
        status: 'active',
      },
      {
        email: 'jennifer.complete@test.com',
        password_hash: hashedPassword,
        phone: '+15551234570',
        phone_verified: true,
        email_verified: true,
        two_factor_enabled: false,
        status: 'active',
      },
      {
        email: 'amanda.new@test.com',
        password_hash: hashedPassword,
        phone: '+15551234571',
        phone_verified: false,
        email_verified: false,
        two_factor_enabled: false,
        status: 'active',
      },
      {
        email: 'michelle.budget@test.com',
        password_hash: hashedPassword,
        phone: '+15551234572',
        phone_verified: true,
        email_verified: true,
        two_factor_enabled: false,
        status: 'active',
      },
      {
        email: 'patricia.schedule@test.com',
        password_hash: hashedPassword,
        phone: '+15551234573',
        phone_verified: true,
        email_verified: true,
        two_factor_enabled: false,
        status: 'active',
      },
      {
        email: 'karen.lifestyle@test.com',
        password_hash: hashedPassword,
        phone: '+15551234574',
        phone_verified: true,
        email_verified: true,
        two_factor_enabled: false,
        status: 'active',
      },
      // E2E Test User - MUST have household for Documents flow tests
      {
        email: 'test@conest.com',
        password_hash: await bcrypt.hash('Test1234!', 10),
        phone: '+15559990000',
        phone_verified: true,
        email_verified: true,
        two_factor_enabled: false,
        status: 'active',
      },
    ])
    .returning('*');

  // Insert profiles - CRITICAL: Only child counts and age ranges, NO names/photos
  await knex('profiles').insert([
    {
      user_id: users[0].id,
      first_name: 'Sarah',
      last_name: 'Johnson',
      bio: 'Working mom of two looking for safe, family-oriented housing. Teacher with predictable schedule.',
      location_city: 'Austin',
      location_state: 'TX',
      location_zip: '78701',
      children_count: 2,
      children_ages_range: '5-10',
      budget_min: 800,
      budget_max: 1200,
      preferred_move_date: new Date('2025-03-01'),
      work_schedule: 'Mon-Fri 8am-4pm',
      parenting_style: 'structured',
      house_rules: JSON.stringify({
        no_smoking: true,
        no_pets: false,
        quiet_hours: '9pm-7am',
        guest_policy: 'weekends_only',
      }),
      lifestyle_preferences: JSON.stringify({
        cleanliness: 'very_clean',
        social_level: 'moderate',
        dietary: 'omnivore',
        exercise: 'regular',
      }),
      verified_id: true,
      verified_income: true,
      verified_background: true,
    },
    {
      user_id: users[1].id,
      first_name: 'Maria',
      last_name: 'Garcia',
      bio: 'Nurse with night shifts, need flexible roommate. Single mom with one toddler.',
      location_city: 'Austin',
      location_state: 'TX',
      location_zip: '78702',
      children_count: 1,
      children_ages_range: '2-4',
      budget_min: 700,
      budget_max: 1000,
      preferred_move_date: new Date('2025-02-15'),
      work_schedule: 'Rotating: 7pm-7am',
      parenting_style: 'relaxed',
      house_rules: JSON.stringify({
        no_smoking: true,
        no_pets: true,
        quiet_hours: '8pm-8am',
        guest_policy: 'ask_first',
      }),
      lifestyle_preferences: JSON.stringify({
        cleanliness: 'moderate',
        social_level: 'low',
        dietary: 'vegetarian',
        exercise: 'occasional',
      }),
      verified_id: true,
      verified_income: true,
      verified_background: true,
    },
    {
      user_id: users[2].id,
      first_name: 'Lisa',
      last_name: 'Chen',
      bio: 'Software engineer working remotely. One school-age child, very organized household.',
      location_city: 'Austin',
      location_state: 'TX',
      location_zip: '78703',
      children_count: 1,
      children_ages_range: '6-8',
      budget_min: 1000,
      budget_max: 1500,
      preferred_move_date: new Date('2025-04-01'),
      work_schedule: 'Remote, flexible',
      parenting_style: 'balanced',
      house_rules: JSON.stringify({
        no_smoking: true,
        no_pets: false,
        quiet_hours: '9pm-7am',
        guest_policy: 'weekends_only',
      }),
      lifestyle_preferences: JSON.stringify({
        cleanliness: 'very_clean',
        social_level: 'moderate',
        dietary: 'omnivore',
        exercise: 'regular',
      }),
      verified_id: true,
      verified_income: false,
      verified_background: false,
    },
    {
      user_id: users[3].id,
      first_name: 'Jennifer',
      last_name: 'Martinez',
      bio: 'Restaurant manager with evening schedule. Three kids, need spacious home.',
      location_city: 'Austin',
      location_state: 'TX',
      location_zip: '78704',
      children_count: 3,
      children_ages_range: '4-12',
      budget_min: 900,
      budget_max: 1300,
      preferred_move_date: new Date('2025-03-15'),
      work_schedule: 'Tue-Sat 2pm-11pm',
      parenting_style: 'structured',
      house_rules: JSON.stringify({
        no_smoking: true,
        no_pets: true,
        quiet_hours: '10pm-7am',
        guest_policy: 'ask_first',
      }),
      lifestyle_preferences: JSON.stringify({
        cleanliness: 'moderate',
        social_level: 'high',
        dietary: 'omnivore',
        exercise: 'occasional',
      }),
      verified_id: true,
      verified_income: true,
      verified_background: true,
    },
    {
      user_id: users[4].id,
      first_name: 'Amanda',
      last_name: 'Wilson',
      bio: 'New to area, accountant seeking stable housing. One infant.',
      location_city: 'Austin',
      location_state: 'TX',
      location_zip: '78705',
      children_count: 1,
      children_ages_range: '0-1',
      budget_min: 600,
      budget_max: 900,
      preferred_move_date: new Date('2025-02-01'),
      work_schedule: 'Mon-Fri 9am-5pm',
      parenting_style: 'balanced',
      house_rules: JSON.stringify({
        no_smoking: true,
        no_pets: false,
        quiet_hours: '8pm-8am',
        guest_policy: 'weekends_only',
      }),
      lifestyle_preferences: JSON.stringify({
        cleanliness: 'very_clean',
        social_level: 'low',
        dietary: 'omnivore',
        exercise: 'none',
      }),
      verified_id: false,
      verified_income: false,
      verified_background: false,
    },
    {
      user_id: users[5].id,
      first_name: 'Michelle',
      last_name: 'Brown',
      bio: 'Retail manager with limited budget but stable income. Two elementary kids.',
      location_city: 'Austin',
      location_state: 'TX',
      location_zip: '78701',
      children_count: 2,
      children_ages_range: '7-9',
      budget_min: 650,
      budget_max: 950,
      preferred_move_date: new Date('2025-03-01'),
      work_schedule: 'Variable retail hours',
      parenting_style: 'relaxed',
      house_rules: JSON.stringify({
        no_smoking: true,
        no_pets: true,
        quiet_hours: '9pm-7am',
        guest_policy: 'anytime',
      }),
      lifestyle_preferences: JSON.stringify({
        cleanliness: 'moderate',
        social_level: 'high',
        dietary: 'omnivore',
        exercise: 'occasional',
      }),
      verified_id: true,
      verified_income: true,
      verified_background: true,
    },
    {
      user_id: users[6].id,
      first_name: 'Patricia',
      last_name: 'Davis',
      bio: 'Freelance designer with flexible schedule. One teenager, quiet household.',
      location_city: 'Austin',
      location_state: 'TX',
      location_zip: '78702',
      children_count: 1,
      children_ages_range: '13-15',
      budget_min: 850,
      budget_max: 1100,
      preferred_move_date: new Date('2025-04-15'),
      work_schedule: 'Self-employed, flexible',
      parenting_style: 'balanced',
      house_rules: JSON.stringify({
        no_smoking: true,
        no_pets: false,
        quiet_hours: '10pm-8am',
        guest_policy: 'weekends_only',
      }),
      lifestyle_preferences: JSON.stringify({
        cleanliness: 'very_clean',
        social_level: 'low',
        dietary: 'vegetarian',
        exercise: 'regular',
      }),
      verified_id: true,
      verified_income: false,
      verified_background: true,
    },
    {
      user_id: users[7].id,
      first_name: 'Karen',
      last_name: 'Anderson',
      bio: 'Yoga instructor and wellness coach. Two young children, health-focused lifestyle.',
      location_city: 'Austin',
      location_state: 'TX',
      location_zip: '78703',
      children_count: 2,
      children_ages_range: '3-6',
      budget_min: 750,
      budget_max: 1050,
      preferred_move_date: new Date('2025-03-01'),
      work_schedule: 'Mon-Sat mornings',
      parenting_style: 'attachment',
      house_rules: JSON.stringify({
        no_smoking: true,
        no_pets: false,
        quiet_hours: '8pm-7am',
        guest_policy: 'ask_first',
      }),
      lifestyle_preferences: JSON.stringify({
        cleanliness: 'very_clean',
        social_level: 'moderate',
        dietary: 'vegan',
        exercise: 'daily',
      }),
      verified_id: true,
      verified_income: true,
      verified_background: true,
    },
    // E2E Test User Profile - for Documents flow tests
    {
      user_id: users[8].id,
      first_name: 'Test',
      last_name: 'User',
      bio: 'E2E test user for automated testing. Parent with one child seeking family-friendly housing.',
      location_city: 'Austin',
      location_state: 'TX',
      location_zip: '78701',
      children_count: 1,
      children_ages_range: '5-7',
      budget_min: 800,
      budget_max: 1200,
      preferred_move_date: new Date('2025-03-01'),
      work_schedule: 'Mon-Fri 9am-5pm',
      parenting_style: 'balanced',
      house_rules: JSON.stringify({
        no_smoking: true,
        no_pets: false,
        quiet_hours: '9pm-7am',
        guest_policy: 'weekends_only',
      }),
      lifestyle_preferences: JSON.stringify({
        cleanliness: 'very_clean',
        social_level: 'moderate',
        dietary: 'omnivore',
        exercise: 'regular',
      }),
      verified_id: true,
      verified_income: true,
      verified_background: true,
    },
  ]);

  console.log('✅ Seed: Test users and profiles created successfully');
}
